### PR TITLE
v3 doc fixes

### PR DESCRIPTION
**Pull request by jlsjonas**
(will commit as I find more inconsistencies, or mark ready for review otherwise)

- Import as VueSwitch for consistency

### CODE REVIEW

**Comment by aocneanu** [comment]
Very well, thank you

**Comment by jlsjonas** [comment]
That should be it for v3.0 related fixes

Should I add something about the just-merged Tag.vue?

**Comment by aocneanu** [comment]
Sure!

**Comment by jlsjonas** [comment]
I'm not sure why this was moved back to in progress (unless you have other reasons not to use "in review") as this PR is ready to be reviewed/merged.

**Comment by aocneanu** [comment]
By mistake. I’ve just got accustomized with github projects...

**Comment by jlsjonas** [comment]
No problem was just wondering :)
I'm quite used to board-based workflows meanwhile.

**Pull request merged**
